version: '3'
services:
  gateway:
    build:
      context: gateway
      args:
        - HOST=0.0.0.0
        - PORT=8080
    ports:
      - 8080:8080
    depends_on:
      - zookeeper
    env_file:
      - .env

  zookeeper:
    build:
      context: zookeeper
    ports:
      - 2181:2181
    env_file:
      - .env