version: '3'
services:
  gateway:
    container_name: gateway
    build:
      context: gateway
      args:
        - HOST=0.0.0.0
        - PORT=8082
    ports:
      - 8082:8082
      - 9103:9100
    depends_on:
      - zookeeper
    env_file:
      - .env

  zookeeper:
    container_name: zookeeper
    build:
      context: zookeeper
    ports:
      - 2181:2181
      - 9102:9100
    env_file:
      - .env
  
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - gateway
    env_file:
      - .env

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3001:3001
    depends_on:
      - prometheus
    env_file:
      - .env
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources

  broker-1:
    container_name: broker-1
    image: minikafka:broker
    ports:
      - 8001:8001
      - 9100:9100
    env_file:
      - .env
    environment:
      - BROKER_HOST=broker-1
      - BROKER_PORT=8001
    depends_on:
      - zookeeper
  
  broker-2:
    container_name: broker-2
    image: minikafka:broker
    ports:
      - 8002:8002
      - 9101:9100
    env_file:
      - .env
    environment:
      - BROKER_HOST=broker-2
      - BROKER_PORT=8002
    depends_on:
      - zookeeper