# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zookeeper.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fzookeeper.proto\"-\n\x10\x44iscoveryRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\"5\n\x11\x44iscoveryResponse\x12 \n\x06status\x18\x01 \x01(\x0e\x32\x10.ZookeeperStatus\"\x10\n\x0eZookeeperEmpty*?\n\x0fZookeeperStatus\x12\x15\n\x11ZOOKEEPER_SUCCESS\x10\x00\x12\x15\n\x11ZOOKEEPER_FAILURE\x10\x01\x32k\n\tZookeeper\x12)\n\x03\x41\x63k\x12\x0f.ZookeeperEmpty\x1a\x0f.ZookeeperEmpty\"\x00\x12\x33\n\x08Register\x12\x11.DiscoveryRequest\x1a\x12.DiscoveryResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zookeeper_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ZOOKEEPERSTATUS']._serialized_start=139
  _globals['_ZOOKEEPERSTATUS']._serialized_end=202
  _globals['_DISCOVERYREQUEST']._serialized_start=19
  _globals['_DISCOVERYREQUEST']._serialized_end=64
  _globals['_DISCOVERYRESPONSE']._serialized_start=66
  _globals['_DISCOVERYRESPONSE']._serialized_end=119
  _globals['_ZOOKEEPEREMPTY']._serialized_start=121
  _globals['_ZOOKEEPEREMPTY']._serialized_end=137
  _globals['_ZOOKEEPER']._serialized_start=204
  _globals['_ZOOKEEPER']._serialized_end=311
# @@protoc_insertion_point(module_scope)
