# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zookeeper.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fzookeeper.proto\"-\n\x10\x44iscoveryRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\",\n\x11\x44iscoveryResponse\x12\x17\n\x06status\x18\x01 \x01(\x0e\x32\x07.Status\"\x07\n\x05\x45mpty*\"\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\x32Y\n\tZookeeper\x12\x17\n\x03\x41\x63k\x12\x06.Empty\x1a\x06.Empty\"\x00\x12\x33\n\x08Register\x12\x11.DiscoveryRequest\x1a\x12.DiscoveryResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zookeeper_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STATUS']._serialized_start=121
  _globals['_STATUS']._serialized_end=155
  _globals['_DISCOVERYREQUEST']._serialized_start=19
  _globals['_DISCOVERYREQUEST']._serialized_end=64
  _globals['_DISCOVERYRESPONSE']._serialized_start=66
  _globals['_DISCOVERYRESPONSE']._serialized_end=110
  _globals['_EMPTY']._serialized_start=112
  _globals['_EMPTY']._serialized_end=119
  _globals['_ZOOKEEPER']._serialized_start=157
  _globals['_ZOOKEEPER']._serialized_end=246
# @@protoc_insertion_point(module_scope)
