# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zookeeper.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fzookeeper.proto\"+\n\x0eReplicaRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2K\n\tZookeeper\x12\x17\n\x03\x41\x63k\x12\x06.Empty\x1a\x06.Empty\"\x00\x12%\n\x08Register\x12\x0f.ReplicaRequest\x1a\x06.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zookeeper_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REPLICAREQUEST']._serialized_start=19
  _globals['_REPLICAREQUEST']._serialized_end=62
  _globals['_EMPTY']._serialized_start=64
  _globals['_EMPTY']._serialized_end=71
  _globals['_ZOOKEEPER']._serialized_start=73
  _globals['_ZOOKEEPER']._serialized_end=148
# @@protoc_insertion_point(module_scope)
