global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: zookeeper
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  scheme: http
  static_configs:
  - targets:
    - zookeeper:8000
    - zookeeper:9100
- job_name: gateway
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  scheme: http
  static_configs:
  - targets:
    - gateway:8000
    - gateway:9100
- job_name: broker-1
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  scheme: http
  static_configs:
  - targets:
    - broker-1:8000
    - broker-1:9100
- job_name: broker-2
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  scheme: http
  static_configs:
  - targets:
    - broker-2:8000
    - broker-2:9100
