apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    {{- include "ci.labels" . | nindent 4 }}
spec:
  type: {{ .Values.zookeeperService.type }}
  ports:
    - port: {{ .Values.zookeeperService.port }}
      targetPort: {{ .Values.zookeeperService.port }}
      protocol: TCP
  selector:
    {{- include "ci.selectorLabels" . | nindent 4 }}
    app: zookeeper
  ipFamilyPolicy: SingleStack
  ipFamilies: ["IPv6"]


