name: deploy
'on':
  workflow_dispatch: null
jobs:
  deploy-back:
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: '${{ secrets.HOST }}'
          username: '${{ secrets.USER }}'
          port: '${{ secrets.PORT }}'
          password: '${{ secrets.PASS }}'
          script: |
            cd sad/MiniKafka
            git checkout master
            git pull origin master
            cd broker
            docker build -t minikafka:broker .
            cd ../
            docker compose up --build -d
